# Rime default settings
# encoding: utf-8

config_version: '0.40'

schema_list:
  - schema: flypy
  - schema: radical_pinyin

switcher:
  caption: OPTION
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
  save_options:
    - ascii_mode
    - traditionalization
    - full_shape
    - emoji
    - ascii_punct
    - simplification
  fold_options: true
  abbreviate_options: true
  option_list_separator: ' / '

ascii_composer:
  good_old_caps_lock: true  # true | false
  switch_key:
    Caps_Lock: clear      # commit_code | commit_text | clear
    Shift_L: commit_code  # commit_code | commit_text | inline_ascii | clear | noop
    Shift_R: commit_code  # commit_code | commit_text | inline_ascii | clear | noop
    Control_L: noop       # commit_code | commit_text | inline_ascii | clear | noop
    Control_R: noop       # commit_code | commit_text | inline_ascii | clear | noop
    Eisu_toggle: clear

menu:
  page_size: 9

punctuator:
  full_shape:
    __include: punctuation:/full_shape
  half_shape:
    __include: punctuation:/half_shape
  symbols:
    __include: symbols:/symbols

key_binder:
  select_first_character: bracketleft
  select_last_character: bracketright
  bindings:
    __patch:
      - key_bindings:/emacs_editing
      - key_bindings:/move_by_word_with_tab
      - key_bindings:/paging_with_minus_equal
      - key_bindings:/paging_with_comma_period
      - key_bindings:/numbered_mode_switch

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
    punct: "/([0-9]|10|[A-Za-z]+)$"
    reverse_lookup: "`[a-z]*'?$"
    gregorian_to_lunar: "^L[0-9]{1,8}"
    number: "^N[0-9]+[.]?[0-9]*"
    unicode: "^U[a-f0-9]+"
